### ISSUE TITLE
Civil connection "BaselineRegion.shape" Freeze

### ISSUE THREAD

**Issue by dschenau85** [paoloemilioserra/CivilConnection#1]
Hi Paola Serra, I have working with Dynamo Revit to bring the Civil corridor in to Revit. But it crash on the note "BaselineRegions.shapes"? Is there a othe
![image](https://user-images.githubusercontent.com/53792273/188586655-d670ecaa-3618-4060-a1fe-d834a6dde343.png)
r way?

**Comment by paoloemilioserra** [comment]
@dschenau85 is this freezing or crashing? can you share the log file?

**Comment by dschenau85** [comment]
Its only freezing and then I have turn off Revit.
Shell is send the Civil3D file? I use the civil3D connection 2022 and Revit 2022

**Comment by paoloemilioserra** [comment]
can you please check that you don't have a Revit half command open that is blocking the execution? please share the log file

**Comment by dschenau85** [comment]
Revit doesn't work with any command. Here is the log
[journal.0013.txt](https://github.com/paoloemilioserra/CivilConnection/files/9495153/journal.0013.txt)

**Comment by paoloemilioserra** [comment]
I need the CivilConnection log

**Comment by dschenau85** [comment]
where can i find that?

**Comment by paoloemilioserra** [comment]
temp folder... have you ever read the instructions?

**Comment by dschenau85** [comment]
[CivilConnection_temp.log](https://github.com/paoloemilioserra/CivilConnection/files/9495377/CivilConnection_temp.log)
yes and you're recordings

**Comment by dschenau85** [comment]
I can not find the file CorridorShapes.xml either. Is that the problem?

**Comment by paoloemilioserra** [comment]
yes! that is the problem, did you test CivilPython?

**Comment by dschenau85** [comment]
No. Can you  give the instruction to use that for this problem?

**Comment by paoloemilioserra** [comment]
...it's on the documentation and there is even a youtube video that explains it

**Comment by dschenau85** [comment]
Thnx. for the help. But it is not working in 2022

**Comment by paoloemilioserra** [comment]
have you tried the latest version of CivilPython?

**Comment by dschenau85** [comment]
Yes i have tried the CivilPython  with Maxseries 24.0 and updated the xml to 24.1 to use in Autodesk Civil3D 2022 but it not recognize the command. What is the latest version support?

**Comment by dschenau85** [comment]
Can you update the CivilPython bundle for Autodesk Civil3D 2022 and 2023?
